# Generated by Django 5.2.3 on 2025-07-23 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='work_title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Work title can only contain letters and numbers.', regex='^[a-zA-Z0-9 ]+$')]),
        ),
    ]
