# Generated by Django 5.2.3 on 2025-08-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pkts',
            options={'verbose_name': 'PKT', 'verbose_name_plural': 'PKT Log'},
        ),
        migrations.AlterModelOptions(
            name='possibleanswers',
            options={'verbose_name': 'Possible Answer', 'verbose_name_plural': 'Possible Answers'},
        ),
        migrations.AlterModelOptions(
            name='processknowledgetest',
            options={'verbose_name': 'PKT instance', 'verbose_name_plural': 'PKT instances'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Question Categories'},
        ),
    ]
